name: cv
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - aom=3.6.0
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - cffi=1.17.1
  - cuda-cccl=13.0.85
  - cuda-cccl_win-64=13.0.85
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=13.0.85
  - cuda-opencl-dev=13.0.85
  - cuda-profiler-api=13.0.85
  - cuda-runtime=12.1.0
  - cuda-version=13.0
  - dav1d=1.2.1
  - expat=2.7.1
  - fontconfig=2.14.1
  - freeglut=3.4.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9f
  - khronos-opencl-icd-loader=2024.05.08
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.1.1
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.4.0.35
  - libcurand-dev=10.4.0.35
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.84.2
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libpng=1.6.39
  - libtiff=4.7.0
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - networkx=3.4.2
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.0.17
  - pcre2=10.42
  - pip=25.0
  - pixman=0.46.4
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.16
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - sympy=1.14.0
  - tbb=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.15.0
  - ucrt=10.0.22621.0
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - asttokens==3.0.0
      - attrs==25.3.0
      - blinker==1.9.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.1
      - cycler==0.12.1
      - dash==3.0.0
      - debugpy==1.8.13
      - decorator==5.2.1
      - deep-sort-realtime==1.3.2
      - defusedxml==0.7.1
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fire==0.7.0
      - flask==3.0.3
      - fonttools==4.56.0
      - fsspec==2025.3.2
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - ipykernel==6.29.5
      - ipython==8.34.0
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - lap==0.5.12
      - lazy-loader==0.4
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - narwhals==1.31.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numpy==2.2.4
      - open3d==0.19.0
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pillow==11.1.0
      - platformdirs==4.3.7
      - plotly==6.0.1
      - polars==1.33.1
      - prompt-toolkit==3.0.50
      - psutil==7.0.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pybboxes==0.1.6
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywin32==310
      - pyzmq==26.3.0
      - referencing==0.36.2
      - requests==2.32.3
      - retrying==1.3.4
      - rpds-py==0.23.1
      - sahi==0.11.22
      - scikit-image==0.25.2
      - scipy==1.15.2
      - seaborn==0.13.2
      - shapely==2.1.0
      - six==1.17.0
      - stack-data==0.6.3
      - stringcase==1.2.0
      - supervision==0.25.1
      - termcolor==3.1.0
      - terminaltables==3.1.10
      - tifffile==2025.3.13
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - ultralytics==8.3.200
      - ultralytics-thop==2.0.14
      - urllib3==2.3.0
      - wcwidth==0.2.13
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - zipp==3.21.0
prefix: C:\Users\alber\.conda\envs\cv
